### PR TITLE
Update/pin requirements.txt versions

### PR DESCRIPTION
**Pull request by hugovk**
Includes https://github.com/meshy/pythonwheels/pull/89 to confirm passes CI ([it does](https://travis-ci.org/hugovk/pythonwheels/builds/283739303)).

The last commit is unique for this PR: https://github.com/meshy/pythonwheels/commit/564b1762417978a6e75cb97f07b9492432efe82d.

### CODE REVIEW

**Comment by meshy** [comment]
Was there a reason that this needed to change? I'd rather keep the versions in `requirements.txt` pinned to specific versions. (I'm surprised that pytz isn't pinned.)

Instead of removing the specific version from this, i'd be more comfortable with changing the version to something more recent.

**Comment by hugovk** [comment]
Main reason was to make sure it still works with the latest version whenever the CI runs, so we don't get any surprises when updating locally, and also to be able to use a more recent version for other projects.

But it's fine to pin both to the latest, and update from time to time. I've updated this PR.

**Comment by ghickman** [comment]
@meshy – you could enable something like dependabot or pyup for this project, depends if you want the overhead of updating requirements weekly.

**Comment by meshy** [comment]
@hugovk @ghickman I'm happy to bump the requirements to the latest version at the moment, but I'm not keen on the idea of updating them regularly without a pressing reason. I think that rules out dependabot, as far as I can see.

Pyup is interesting though. A security update could seem like a reasonable justification for automating updates. I'll install it, and see what happens!

**Comment by meshy** [comment]
@hugovk any chance you could rebase `master` into this so that I can merge the requirements changes?

If not, don't worry, I'll use #92 instead, but I prefer yours because you've pinned `pytz`.

**Comment by hugovk** [comment]
@meshy Rebased.

**Comment by meshy** [comment]
Thank you `:)`

**Pull request merged**
